version: "3"

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grants_stack_indexer
  # datadog:
  #   image: datadog/agent:latest
  #   # network_mode: "host"        
  #   env_file:
  #     - .env
  #   environment:
  #     - DD_API_KEY=${DD_API_KEY}
  #     - DD_APM_ENABLED=false
  #     - DD_LOGS_ENABLED=false
  #     - DD_ENV=${DD_ENV}
  #     - DD_SERVICE=indexer
  #     - DD_USE_DOGSTATSD=true
  #     - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
  #     - DD_HOSTNAME_TRUST_UTS_NAMESPACE=true
  #     - DD_VERSION=1.0.0


  #   ports:
  #     - "8126:8126" # APM port
  #     - "8125:8125/udp" # DogStatsD port
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro