apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: indexer-web
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8080
  selector:
    app: indexer-web
