apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: indexer-web-hpa
  namespace: backend-web

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: indexer-web
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 # percentage
