name: Check Pull Request

on:
  pull_request:
    branches: "**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      # (ab)use the development environment until we build on github
      - name: Build and test
        run: |
          flyctl -c fly.staging.toml deploy --remote-only --build-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}


